manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: hummingbird
      remote: zmkfirmware
      revision: main
      import: app/west.yml

  self:
    path: config/modules/hummingbird