manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      remote: zmkfirmwarerm -rf /workspaces/zmk-config-MicroGaming/
      import: app/west.yml

  self:
    path: config